server:
  port: 8888
  servlet:
    context-path: /shop-manager

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    # 指定druid连接池以及连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1   # 初始连接数
      max-active: 20    # 最大连接数
      max-idle: 20      # 最大空闲
      min-idle: 1       # 最小空闲
      max-wait: 60000   # 最长等待时间
  # freemarker 模板引擎
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html;charset=UTF-8
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/views/
    # 配置模板里是否可以直接取request属性 request是别名
    request-context-attribute: request
    # 配置将request和session中的键值添加到AbstractTemplateView类的renderMergedOutputModel方法中model这个map参数中
    expose-request-attributes: true
    expose-spring-macro-helpers: true
    # 配置模板里是否可以直接去session的属性 ture是允许
    expose-session-attributes: true
    settings:
      tag_syntax: auto_detect               # 配置语法标签为自动，页面可以将 <> 改为 [] ，为了区别html标签
      template_update_delay: 0              # 模板更新时间，单位秒
      default_encoding: UTF-8               # 默认编码字符集
      output_encoding: UTF-8                # 模板输出编码字符集
      locale: zh_CN                         # 本地化配置
      date_format: yyyy-MM-dd               # 日期格式化
      time_format: HH:mm:ss                 # 时间格式化
      datetime_format: yyyy-MM-dd HH:mm:ss  # 日期时间格式化
      number_format: #.##                   # 数字格式化
      boolean_format: true,false            # boolean格式化
      template_exception_handler: html_debug
      classic_compatible: true

mybatis:
  type-aliases-package: com.chris.manager.pojo
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.chris.manager.mapper: debug
